### PR TITLE
Hotfix/requests below the period with fix

### PR DESCRIPTION
**Pull request by lloydmeta**
@urbanautomaton seems a bit busy so I thought I would polish this off.

### CODE REVIEW

**Comment by lloydmeta** [comment]
Continuation of #5

**Comment by xevix** [comment]
@lloydmeta Awesome, thanks! One slight thing would be to maybe lower the number of seconds for the rspec test to the near-minimum required to trigger the error, since this will be run every time rspec runs tests.

**Comment by lloydmeta** [comment]
Good idea. Done.

**Comment by xevix** [comment]
Awesome, thanks!

**Pull request merged**
