### PR TITLE
Allow for :if condition in middleware configuration

### PR DESCRIPTION
**Pull request by smt116**
This is a case when you want to skip rate limit check in some situations. For example in a specific environment.

---

I have also replaced sleeps in specs with time cop:

```
Finished in 0.37195 seconds (files took 0.3298 seconds to load)
10 examples, 0 failures
```

vs

```
Finished in 4.45 seconds (files took 0.54342 seconds to load)
10 examples, 0 failures
```

### CODE REVIEW

**Comment by smt116** [comment]
@xevix any news on that pull request? :)

**Comment by xevix** [comment]
@smt116 Hey there, sorry for the delay.

`use Grape::Middleware::ThrottleMiddleware, cache: Redis.new, if: -> { ENV.fetch("RACK_ENV").eql?("production") }`

Calling a method every single time an endpoint gets hit is a big penalty I feel. Perhaps making this into a boolean expression makes more sense, as this is a config/setup condition, and is unlikely to change at runtime.

**Comment by xevix** [comment]
Another alternative is to create a noop middleware that uses the same throttle name but does nothing, and to use standard Ruby logic to pick to use that one instead. This involves minimal coding overhead and is more explicit.

**Comment by smt116** [comment]
I have switched to [rack-attack](https://github.com/kickstarter/rack-attack). Now I am using middleware for rate limiting only in the `config.ru`. I think that it is more "configurable".

**Comment by xevix** [comment]
Yeah, it seems rack-attack has become a thing recently (I myself haven't been too active in Ruby development recently). Perhaps it makes sense to simply integrate it with Grape.

**Pull request closed without merging**
