### PR TITLE
added reds.ping and rescue block

### PR DESCRIPTION
**Pull request by chrisdebruin**
hope you can merge this, let me know what you think.

Cheers

### CODE REVIEW

**Comment by xevix** [comment]
Hey, thanks for the PR. Definitely a good idea to check for Redis being alive. Can you check if there's some way to add a test for this behavior? Currently using fake redis in tests.

If you're going to use a logger to write the exception, it might be worth allowing users to set a logger to use, as is common practice in frameworks like Rails/Padrino that use their own logger and may not want to go to STDOUT.

**Comment by chrisdebruin** [comment]
good points, I'll add the logger part. Tried to write spec for the case when redis is unavailable but have a hard time to let fakeredis 'believe' that redis is down. Any ideas?

**Comment by chrisdebruin** [comment]
never mind, fixed it. Please check updated code. Thnx

**Comment by xevix** [comment]
@chrisdebruin Awesome, nice find on the Redis-down testing. One final thing is that I think we can get away without testing if we log a message, so I've removed it. Other than that, looks great. Thanks for the hard work.

Merged via dad28d9a661d7d825c5426d8c348b97cffbf5421.

**Comment by xevix** [comment]
@chrisdebruin Actually, if you have the time, could you add a bit in the README about the new `logger` param that can be set on the middleware? If not, I'll add it later. Thanks.

**Pull request closed without merging**
